
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.19.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.19.0
    - run: npm install
    - run: npm run build
