
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: ./demo/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - name: Deploy to Netlify
      uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        NETLIFY_AUTH_TOKEN: WA2Ik4YjneZhAgOAYehgVQMXCAGmLoQTscR2L3CgpI4
        NETLIFY_DEPLOY_TO_PROD: true
        NETLIFY_SITE_ID: e3f9eb1f-7366-4492-9f4b-df33917eb7ad
        BUILD_COMMAND: "echo hello"
        INSTALL_COMMAND: "echo hello"
        BUILD_DIRECTORY: 'demo/build'
