
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15x, 14x, 16x]

    steps:
    - uses: actions/checkout@v2
    - run: cd demo
    - run: npm install
    - run: npm run build 
    - run: npm test
